### ISSUE TITLE
Tests failing due to dependency issues

### ISSUE THREAD

**Issue by sandrich** [sandrich/classifying_digits_mnist#6]
Tests are failing due to dependency issues

```
======================================================================
ERROR: test_app (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_app
Traceback (most recent call last):
  File "/opt/conda/envs/mnist_classifier/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/envs/mnist_classifier/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/root/project/tests/test_app.py", line 2, in <module>
    from src import app
  File "/root/project/src/app.py", line 1, in <module>
    import dataset
ModuleNotFoundError: No module named 'dataset'


======================================================================ttest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dataset
Traceback (most recent call last):
  File "/opt/conda/envs/mnist_classifier/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/envs/mnist_classifier/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/root/project/tests/test_dataset.py", line 6, in <module>
    from src import dataset
  File "/root/project/src/dataset.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
ERROR: test_dataset (uni
```

**Comment by sandrich** [comment]
Closed with #7
